# 1 "data/maps/OakHouse_B1F/scripts.pory"

# 2 "data/maps/OakHouse_B1F/scripts.pory"
OakHouse_B1F_MapScripts::
# 3 "data/maps/OakHouse_B1F/scripts.pory"
	.byte 0

Oak_House_2F_Event_Script_Old_TV::
	return


Oak_House_2F_Event_Script_Headless_Doll::
	return


Oak_House_2F_Event_Script_Ramshackled_Table_Set::
	return


Oak_House_2F_Event_Script_Crusty_Tea_Cup::
	return


Oak_House_2F_Event_Script_Rickety_Bedframe::
	return

