# 1 "data/maps/PalletTown_ChaosRoom/scripts.pory"

# 2 "data/maps/PalletTown_ChaosRoom/scripts.pory"
PalletTown_ChaosRoom_MapScripts::
# 3 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	.byte 0

PalletTown_ChaosRoom_EventScript_Ghost::
# 7 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	lock
# 8 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	playse SE_LISA
# 9 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	release
	end


PalletTown_ChaosRoom_EventScript_Ghost2::
# 14 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	lock
# 15 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	playse SE_LISA_2
# 16 "data/maps/PalletTown_ChaosRoom/scripts.pory"
	release
	end

